---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  name: 4-demo-source-bucket-bb-app
  namespace: flux-system
spec:
  bucketName: myss-test
  endpoint: s3.amazonaws.com
  insecure: true
  interval: 10s
  provider: aws
  region: eu-west-2
  secretRef:
    name: aws-user-creds
