---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 4-demo-kustomize-s3bucket-bb-app
  namespace: flux-system
spec:
  interval: 10s
  path: ./
  prune: true
  sourceRef:
    kind: Bucket
    name: 4-demo-source-bucket-bb-app
  targetNamespace: 4-demo
