---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: 5-demo-helm-release-git-bb-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 5-demo-source-git-helm-bb-ap
  interval: 10s
  targetNamespace: 5-demo
  values:
    labels:
      app:
        env: dev
        name: block-buster
        version: 7.6.0
    namespace:
      name: 6-demo
    replicaCount: 1
    service:
      nodePort: 30006
      type: NodePort
