---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: 7-demo-source-oci-bb-app-7-7-0
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  ref:
    tag: new
  secretRef:
    name: ghcr-auth
  url: oci://ghcr.io/shankarsrinivasnew/bb-app
