---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 8-demo-source-git-bb-app
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: 8-demo
  secretRef:
    name: github-auth.yaml
  url: https://github.com/shankarsrinivasnew/bb-app-source.git
