---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: notification-provider-slack
  namespace: flux-system
spec:
  address: https://hooks.slack.com/services/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
  channel: flux-alerts-channel
  secretRef:
    name: flux-slack-bot-token
  type: slack
  username: flux-bot
