---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: notification-alert-slack
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: flux-system
  - kind: Kustomization
    name: 2-demo-kustomize-git-bb-app
  - kind: GitRepository
    name: 2-demo-source-git-bb-app
  providerRef:
    name: notification-provider-slack
