---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: notification-provider-slack
  namespace: flux-system
spec:
  address: https://slack.com/api/chat.PostMessage
  channel: flux-alerts-channel
  secretRef:
    name: flux-slack-bot-token
  type: slack
  username: flux-bot
